#spring.application.name=APIGateway
#server.port = 8010
#
#spring.cloud.gateway.discovery.locator.enable=true
#
#spring.cloud.gateway.routes.id= USER
#spring.cloud.gateway.routes.uri = http://localhost:8020/user
#spring.cloud.gateway.routes.path = /user/**